Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PreInfoTrans.Data;
using PreInfoTrans.Models;
namespace PreInfoTrans.Controllers
{
    [Authorize(Roles = "Администратор")]
    public class AdminController : Controller
    {
        private readonly AppDbContext _context;
        
        public AdminController(AppDbContext context)
        {
            _context = context;
        }
        // GET: AdminController
        public ActionResult Index()
        {
            // Выполните объединение таблиц AspNetUsers и AspNetUserRoles
            var usersWithRoles = (from user in _context.Users
                                  join userRole in _context.UserRoles on user.Id equals userRole.UserId into userRolesGroup
                                  from userRole in userRolesGroup.DefaultIfEmpty() // Левое соединение
                                  join role in _context.Roles on userRole.RoleId equals role.Id into rolesGroup
                                  from role in rolesGroup.DefaultIfEmpty() // Левое соединение
                                  select new UserWithRoleViewModel
                                  {
                                      UserId = user.Id,
                                      UserName = user.UserName,
                                      Email = user.Email,
                                      RoleName = role == null ? "Не назначена" : role.Name
                                  }).ToList();

            return View(usersWithRoles);
        }

        // GET: AdminController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdminController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminController/Edit/5
        public IActionResult Edit(string userId)
        {
            // Получаем пользователя по его идентификатору
            var user = _context.Users.FirstOrDefault(u => u.Id == userId);
            if (user == null)
            {
                return NotFound();
            }

            // Получаем список ролей
            var roles = _context.Roles.ToList();

            // Получаем текущую роль пользователя
            var userRole = _context.UserRoles.FirstOrDefault(ur => ur.UserId == userId);

            // Формируем список ролей в виде SelectList
            var roleList = new SelectList(roles, "Id", "Name", userRole?.RoleId);

            // Создаем модель представления
            var viewModel = new UserEditViewModel
            {
                UserId = user.Id,
                UserName = user.UserName,
                Email = user.Email,
                
                RoleId = userRole?.RoleId,
                Roles = roleList
            };

            return View(viewModel);
        }

        // POST: AdminController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserEditViewModel model, string roleId)
        {
            // Присваиваем значение RoleId из параметра roleId модели
            model.RoleId = roleId;
            foreach (var modelState in ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    Console.WriteLine(error.ErrorMessage);
                }
            }
            if (!ModelState.IsValid)
            {
                // Если модель не прошла валидацию, возвращаем представление снова с модель   
                return View(model);
            }
            
            // Получаем пользователя по его идентификатору
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == model.UserId);
            if (user == null)
            {
                return NotFound();
            }

            // Получаем текущую роль пользователя
            var userRole = await _context.UserRoles.FirstOrDefaultAsync(ur => ur.UserId == model.UserId);

            if (userRole != null)
            {
                // Удаляем текущую роль пользователя
                _context.UserRoles.Remove(userRole);
                await _context.SaveChangesAsync();
            }

            if (!string.IsNullOrEmpty(model.RoleId))
            {
                // Добавляем новую роль пользователю
                var newUserRole = new IdentityUserRole<string>
                {
                    UserId = user.Id,
                    RoleId = model.RoleId
                };
                _context.UserRoles.Add(newUserRole);
                await _context.SaveChangesAsync();
            }

            // После изменения роли пользователя перенаправляем на страницу списка пользователей
            return RedirectToAction("Index");
        }

        // GET: AdminController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AdminController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/EpisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PreInfoTrans.Data;
using PreInfoTrans.Models;

namespace PreInfoTrans.Controllers
{
    [Authorize]
    public class EpisController : Controller
    {

        private readonly EpiDbContext _context;


        public List<Tsmp>? tsmps;
        public EpisController(EpiDbContext context)
        {
            _context = context;         
        }

        // GET: Epis
        [Authorize(Roles = "Администратор, Сотрудник, Руководитель")]
        public async Task<IActionResult> Index()
        {
            IQueryable<Epi> query = _context.Epi;

            // Если пользователь имеет роль Сотрудник, фильтруем Epi по полю CreatorId
            if (User.IsInRole("Сотрудник"))
            {
                query = query.Where(e => e.CreatorId == User.Identity.Name);
            }

            // Получаем список Epi
            List<Epi> epis = await query.ToListAsync();
            return _context.Epi != null ?
                        View(epis) :
                        Problem("Не возможно получить список ЭПИ");
        }

        [Authorize(Roles = "Администратор, Сотрудник, Руководитель")]
        public async Task<IActionResult> Isto()
        {
            return _context.Epi != null ?
                        View(await _context.Epi.Where(t =>  (t.Result == Result.Pending) || (t.Result == Result.Registration) || ((t.Result == Result.Release) && (t.RegEndDate == null))).ToListAsync()) :
                        Problem("Entity set 'EpiDbContext.Epi'  is null.");
        }

        // GET: Epis/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Epi == null)
            {
                return NotFound();
            }

            var epi = await _context.Epi
                .FirstOrDefaultAsync(m => m.Id == id);
            if (epi == null)
            {
                return NotFound();
            }
            List<Tsmp> tsmpsModel = _context.Tsmp.Where(c => c.EpiDocName == epi.DocName).ToList();
            Carrier carrier = _context.Carrier.Where(c => c.EpiId == id).FirstOrDefault();
            Owner owner = _context.Owner.Where(c => c.EpiId == id).FirstOrDefault();
            epi.TsmpFormatedString = string.Join("/", tsmpsModel.Select(t => t.RegNum));

            EpiTsmsViewModel epiTsmsViewModel = new EpiTsmsViewModel
            {
                EpiDocName = epi.DocName,
                Epi = epi,
                Carrier = carrier,
                Owner = owner,
                Tsmps = tsmpsModel
            };
            return View(epiTsmsViewModel);
        }

        // GET: Epis/Print/5
        public async Task<IActionResult> Print(int? id)
        {
            if (id == null || _context.Epi == null)
            {
                return NotFound();
            }

            var epi = await _context.Epi
                .FirstOrDefaultAsync(m => m.Id == id);
            if (epi == null)
            {
                return NotFound();
            }

            if (epi.Result == Result.Canceling)
            {
                return RedirectToAction("Index");
            }

            List<Tsmp> tsmpsModel = _context.Tsmp.Where(c => c.EpiDocName == epi.DocName).ToList();
            Carrier carrier = _context.Carrier.Where(c => c.EpiId == id).FirstOrDefault();
            Owner owner = _context.Owner.Where(c => c.EpiId == id).FirstOrDefault();
            epi.TsmpFormatedString = BusinessLogic.EpiLogic.GetTsmpFormatedString(tsmpsModel);

            EpiTsmsViewModel epiTsmsViewModel = new EpiTsmsViewModel
            {
                EpiDocName = epi.DocName,
                Epi = epi,
                Carrier = carrier,
                Owner = owner,
                Tsmps = tsmpsModel
            };
            return View(epiTsmsViewModel);
        }

        // GET: Epis/Create
        [Authorize(Roles = "Сотрудник")]
        public IActionResult Create()
        {
            var epi = new Epi();

            epi.DocDate = DateTime.Now;
            epi.Result = Result.Created;
            epi.IsPassengers = 0;
            epi.IsCrew = 0;
            epi.Targets = null;
            epi.CreatorId = User.Identity?.Name;
            _context.Add(epi);
            _context.SaveChanges();
            int id = epi.Id;
            epi.DocName = id.ToString().PadLeft(7, '0');
            _context.SaveChanges();
            return RedirectToAction(nameof(Edit), new { id = id });
        }

        // GET: Epis/Edit/5
        [Authorize(Roles = "Сотрудник")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Epi == null)
            {
                return NotFound();
            }

            var epi = await _context.Epi.FindAsync(id);
            if (epi == null)
            {
                return NotFound();
            }
            if (epi.CreatorId != User.Identity?.Name) 
            {
                TempData["Message"] = $"Нельзя редактировать чужую ЭПИ!";
                return RedirectToAction("Index");
            }
            if (epi.Result != Result.Created) 
            {
                var resText = "";
                switch (epi.Result) 
                {
                    case Result.Canceling:
                        resText = "Аннулирование";
                        break;
                    case Result.Deleted:
                        resText = "Удалено";
                        break;
                    case Result.Denied:
                        resText = "Отказ регистрации";
                        break;
                    case Result.Pending:
                        resText = "Направлена в ИСТО";
                        break;
                    case Result.Refused:
                        resText = "Отказ выпуска";
                        break;
                    case Result.Registration:
                        resText = "Регистрация";
                        break;
                    case Result.Release:
                        resText = "Выпуск";
                        break;
                    case Result.Revoked:
                        resText = "Отозвана";
                        break;
                    case Result.Revoking:
                        resText = "Отзыв";
                        break;
                    default:
                        resText = "не известно";
                        break;
                }
                TempData["Message"] = $"ЭПИ в статусе {resText} редактировать нельзя!";
                return RedirectToAction("Index");
            }

            List<Tsmp> tsmpsModel = await _context.Tsmp.Where(c => c.EpiDocName == epi.DocName).ToListAsync();
            Carrier carrier = await _context.Carrier.Where(c => c.EpiId == id).FirstOrDefaultAsync();
            Owner owner = await _context.Owner.Where(c => c.EpiId == id).FirstOrDefaultAsync();
            List<Countries> countries = await _context.Countries.ToListAsync();
            var onlyCountriesNames = countries.GroupBy(n => new { n.CountryName }).Select(g => g.First()).ToList();
            EpiTsmsViewModel epiTsmsViewModel = new EpiTsmsViewModel
            {
                EpiDocName = epi.DocName,
                Carrier = carrier,
                Owner = owner,
                Countries = countries,
                Epi = epi,
                Tsmps = tsmpsModel
            };
            List<TsmpTypes> allTsmps = await _context.TsmpTypes.ToListAsync();
            // Группируем записи по полю TypeName и проецируем результат, чтобы получить только названия групп и их коды
            var uniqueTypes = allTsmps.GroupBy(t => new { t.TypeCode, t.TypeName })
                                      .Select(g => g.First())
                                      .ToList();
            ViewData["Tska"] = tsmpsModel;
            ViewData["UniqueTypes"] = uniqueTypes;
            ViewData["Countries"] = onlyCountriesNames;
            ViewData["Carrier"] = carrier != null ? carrier.GetAllFieldsAsString() : "";
            ViewData["Owner"] = owner != null ? owner.GetAllFieldsAsString() : "";
            return View(epi);
        }

        // POST: Epis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Сотрудник")]
        public async Task<IActionResult> Edit(int id, Epi epi)
        {
            
            if (id != epi.Id)
            {
                return NotFound();
            }

            List<Tsmp> tfslist = await _context.Tsmp.Where(t=>t.EpiDocName==epi.DocName).ToListAsync();
            if (tfslist.Count == 0)
            {
                TempData["Message"] = $"Не добавлено ни одного ТСМП!";
                return RedirectToAction("Edit", id);
            }

            var carrier = await _context.Carrier.Where(c => c.EpiId == epi.Id).FirstOrDefaultAsync();
            if (carrier == null)
            {
                TempData["Message"] = $"Не заполнены данные о лице, осуществляющем перевозку!";
                return RedirectToAction("Edit", id);
            }

            var owner = await _context.Owner.Where(c => c.EpiId == epi.Id).FirstOrDefaultAsync();
            if (tfslist[0].TypeCode != 20) 
            {
                if (owner == null)
                {
                    TempData["Message"] = $"Не заполнены данные о лице, ответственном за использование транспортного средства!";
                    return RedirectToAction("Edit", id);
                }
            }

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager

@{
    bool isAdmin = User.Identity.IsAuthenticated && UserManager.IsInRoleAsync(await UserManager.GetUserAsync(User), "Администратор").Result;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PreInfoTrans</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PreInfoTrans.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> *@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3 bg-gradient" style="background-color: #125b50;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Epis" asp-action="Index">ПреИнфоТранс</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <li class="nav-item dropdown">
                            <a class="nav-link text-light dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Отчёты</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Epis" asp-action="Report1">Отчет по ЭПИ с истекшим сроком</a></li>
                                <li><a class="dropdown-item" asp-controller="Epis" asp-action="Report2">Отчет по контролю сроков</a></li>
                                @* <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Epis" asp-action="Reports">Сводный отчёт</a></li> *@
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Epis" asp-action="Charts">Графики</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Help">Инструкции</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Epis" asp-action="Isto">ИСТО</a>
                        </li>
                        @if (isAdmin)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Admin" asp-action="Index">Управление пользователями</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - <a class="text-muted" href="/">PreInfoTrans</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>