Models/ChartsViewModel.cs
namespace PreInfoTrans.Models
{
    public class ChartsViewModel
    {
        public List<EpiUsersViewModel>? epiUsersViewModels { get; set; }
        public List<EpiResultViewModel>? epiResultViewModels { get; set; }
        public int barWidth {  get; set; }
    }
}

Controllers/EpisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PreInfoTrans.Data;
using PreInfoTrans.Models;

namespace PreInfoTrans.Controllers
{
    [Authorize]
    public class EpisController : Controller
    {

        private readonly EpiDbContext _context;


        public List<Tsmp>? tsmps;
        public EpisController(EpiDbContext context)
        {
            _context = context;         
        }

        // GET: Epis
        [Authorize(Roles = "Администратор, Сотрудник, Руководитель")]
        public async Task<IActionResult> Index()
        {
            IQueryable<Epi> query = _context.Epi;

            // Если пользователь имеет роль Сотрудник, фильтруем Epi по полю CreatorId
            if (User.IsInRole("Сотрудник"))
            {
                query = query.Where(e => e.CreatorId == User.Identity.Name);
            }

            // Получаем список Epi
            List<Epi> epis = await query.ToListAsync();
            return _context.Epi != null ?
                        View(epis) :
                        Problem("Не возможно получить список ЭПИ");
        }

        [Authorize(Roles = "Администратор, Сотрудник, Руководитель")]
        public async Task<IActionResult> Isto()
        {
            return _context.Epi != null ?
                        View(await _context.Epi.Where(t =>  (t.Result == Result.Pending) || (t.Result == Result.Registration) || ((t.Result == Result.Release) && (t.RegEndDate == null))).ToListAsync()) :
                        Problem("Entity set 'EpiDbContext.Epi'  is null.");
        }

        // GET: Epis/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Epi == null)
            {
                return NotFound();
            }

            var epi = await _context.Epi
                .FirstOrDefaultAsync(m => m.Id == id);
            if (epi == null)
            {
                return NotFound();
            }
            List<Tsmp> tsmpsModel = _context.Tsmp.Where(c => c.EpiDocName == epi.DocName).ToList();
            Carrier carrier = _context.Carrier.Where(c => c.EpiId == id).FirstOrDefault();
            Owner owner = _context.Owner.Where(c => c.EpiId == id).FirstOrDefault();
            epi.TsmpFormatedString = string.Join("/", tsmpsModel.Select(t => t.RegNum));

            EpiTsmsViewModel epiTsmsViewModel = new EpiTsmsViewModel
            {
                EpiDocName = epi.DocName,
                Epi = epi,
                Carrier = carrier,
                Owner = owner,
                Tsmps = tsmpsModel
            };
            return View(epiTsmsViewModel);
        }

        // GET: Epis/Print/5
        public async Task<IActionResult> Print(int? id)
        {
            if (id == null || _context.Epi == null)
            {
                return NotFound();
            }

            var epi = await _context.Epi
                .FirstOrDefaultAsync(m => m.Id == id);
            if (epi == null)
            {
                return NotFound();
            }

            if (epi.Result == Result.Canceling)
            {
                return RedirectToAction("Index");
            }

            List<Tsmp> tsmpsModel = _context.Tsmp.Where(c => c.EpiDocName == epi.DocName).ToList();
            Carrier carrier = _context.Carrier.Where(c => c.EpiId == id).FirstOrDefault();
            Owner owner = _context.Owner.Where(c => c.EpiId == id).FirstOrDefault();
            epi.TsmpFormatedString = BusinessLogic.EpiLogic.GetTsmpFormatedString(tsmpsModel);

            EpiTsmsViewModel epiTsmsViewModel = new EpiTsmsViewModel
            {
                EpiDocName = epi.DocName,
                Epi = epi,
                Carrier = carrier,
                Owner = owner,
                Tsmps = tsmpsModel
            };
            return View(epiTsmsViewModel);
        }

        // GET: Epis/Create
        [Authorize(Roles = "Сотрудник")]
        public IActionResult Create()
        {
            var epi = new Epi();

            epi.DocDate = DateTime.Now;
            epi.Result = Result.Created;
            epi.IsPassengers = 0;
            epi.IsCrew = 0;
            epi.Targets = null;
            epi.CreatorId = User.Identity?.Name;
            _context.Add(epi);
            _context.SaveChanges();
            int id = epi.Id;
            epi.DocName = id.ToString().PadLeft(7, '0');
            _context.SaveChanges();
            return RedirectToAction(nameof(Edit), new { id = id });
        }

        // GET: Epis/Edit/5
        [Authorize(Roles = "Сотрудник")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Epi == null)
            {
                return NotFound();
            }

            var epi = await _context.Epi.FindAsync(id);
            if (epi == null)
            {
                return NotFound();
            }
            if (epi.CreatorId != User.Identity?.Name) 
            {
                TempData["Message"] = $"Нельзя редактировать чужую ЭПИ!";
                return RedirectToAction("Index");
            }
            if (epi.Result != Result.Created) 
            {
                var resText = "";
                switch (epi.Result) 
                {
                    case Result.Canceling:
                        resText = "Аннулирование";
                        break;
                    case Result.Deleted:
                        resText = "Удалено";
                        break;
                    case Result.Denied:
                        resText = "Отказ регистрации";
                        break;
                    case Result.Pending:
                        resText = "Направлена в ИСТО";
                        break;
                    case Result.Refused:
                        resText = "Отказ выпуска";
                        break;
                    case Result.Registration:
                        resText = "Регистрация";
                        break;
                    case Result.Release:
                        resText = "Выпуск";
                        break;
                    case Result.Revoked:
                        resText = "Отозвана";
                        break;
                    case Result.Revoking:
                        resText = "Отзыв";
                        break;
                    default:
                        resText = "не известно";
                        break;
                }
                TempData["Message"] = $"ЭПИ в статусе {resText} редактировать нельзя!";
                return RedirectToAction("Index");
            }

            List<Tsmp> tsmpsModel = await _context.Tsmp.Where(c => c.EpiDocName == epi.DocName).ToListAsync();
            Carrier carrier = await _context.Carrier.Where(c => c.EpiId == id).FirstOrDefaultAsync();
            Owner owner = await _context.Owner.Where(c => c.EpiId == id).FirstOrDefaultAsync();
            List<Countries> countries = await _context.Countries.ToListAsync();
            var onlyCountriesNames = countries.GroupBy(n => new { n.CountryName }).Select(g => g.First()).ToList();
            EpiTsmsViewModel epiTsmsViewModel = new EpiTsmsViewModel
            {
                EpiDocName = epi.DocName,
                Carrier = carrier,
                Owner = owner,
                Countries = countries,
                Epi = epi,
                Tsmps = tsmpsModel
            };
            List<TsmpTypes> allTsmps = await _context.TsmpTypes.ToListAsync();
            // Группируем записи по полю TypeName и проецируем результат, чтобы получить только названия групп и их коды
            var uniqueTypes = allTsmps.GroupBy(t => new { t.TypeCode, t.TypeName })
                                      .Select(g => g.First())
                                      .ToList();
            ViewData["Tska"] = tsmpsModel;
            ViewData["UniqueTypes"] = uniqueTypes;
            ViewData["Countries"] = onlyCountriesNames;
            ViewData["Carrier"] = carrier != null ? carrier.GetAllFieldsAsString() : "";
            ViewData["Owner"] = owner != null ? owner.GetAllFieldsAsString() : "";
            return View(epi);
        }

        // POST: Epis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Сотрудник")]
        public async Task<IActionResult> Edit(int id, Epi epi)
        {
            
            if (id != epi.Id)
            {
                return NotFound();
            }

            List<Tsmp> tfslist = await _context.Tsmp.Where(t=>t.EpiDocName==epi.DocName).ToListAsync();
            if (tfslist.Count == 0)
            {
                TempData["Message"] = $"Не добавлено ни одного ТСМП!";
                return RedirectToAction("Edit", id);
            }

            var carrier = await _context.Carrier.Where(c => c.EpiId == epi.Id).FirstOrDefaultAsync();
            if (carrier == null)
            {
                TempData["Message"] = $"Не заполнены данные о лице, осуществляющем перевозку!";
                return RedirectToAction("Edit", id);
            }

            var owner = await _context.Owner.Where(c => c.EpiId == epi.Id).FirstOrDefaultAsync();
            if (tfslist[0].TypeCode != 20) 
            {
                if (owner == null)
                {
                    TempData["Message"] = $"Не заполнены данные о лице, ответственном за использование транспортного средства!";
                    return RedirectToAction("Edit", id);
                }
            }

Controllers/TsmpsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PreInfoTrans.Data;
using PreInfoTrans.Models;

namespace PreInfoTrans.Controllers
{
    [Authorize]
    public class TsmpsController : Controller
    {
        private readonly EpiDbContext _context;

        public TsmpsController(EpiDbContext context)
        {
            _context = context;
        }

        // GET: Tsmps/Create
        public IActionResult Create(string? docname, int? tsmptype)
        {
            Tsmp tsmp = new Tsmp() { TypeCode = (int)tsmptype };
            List<TsmpTypes> types = _context.TsmpTypes.Where(t => t.TypeCode == tsmptype).ToList();
            List<Countries> countries = _context.Countries.ToList();
            List<Brands> brands = _context.Brands.ToList();
            TsmpTypesViewModel tsmpTypesViewModel = new TsmpTypesViewModel
            {
                TsmpTypes = types,
                Brands = brands,
                Countries = countries,
                Tsmp = tsmp,
                DocName = docname
            };
            tsmp.EpiDocName = docname;
            return View(tsmpTypesViewModel);
        }

        // POST: Tsmps/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Brand,Model,Type,TypeCode,RegNum,RegCountry,VinCode,EpiDocName")] Tsmp tsmp)
        {
            //tsmp.Type = HttpContext.Request.Form["SelectedName"].ToString().Split(':')[1];
           // tsmp = BusinessLogic.Utils.CheckType(HttpContext.Request.Form["SelectedName"].ToString(), tsmp);
            if (ModelState.IsValid)
            {
                if (tsmp.TypeCode == 30 && tsmp.VinCode.Length == 17) 
                {
                    var _vin = tsmp.VinCode?.ToUpper();
                    tsmp.VinCode = _vin;
                }
                
                _context.Add(tsmp);
                await _context.SaveChangesAsync();
                return RedirectToAction("Edit", "Epis", new { Id = Int32.Parse(tsmp.EpiDocName)});
            }
            List<TsmpTypes> types = _context.TsmpTypes.Where(t => t.TypeCode == tsmp.TypeCode).ToList();
            List<Countries> countries = _context.Countries.ToList();
            List<Brands> brands = _context.Brands.ToList();
            TsmpTypesViewModel tsmpTypesViewModel = new TsmpTypesViewModel
            {
                TsmpTypes = types,
                Brands = brands,
                Countries = countries,
                Tsmp = tsmp,
                DocName = tsmp.EpiDocName
            };
            return View(tsmpTypesViewModel);
        }

        // GET: Tsmps/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tsmp == null)
            {
                return NotFound();
            }

            var tsmp = await _context.Tsmp.FindAsync(id);
            if (tsmp == null)
            {
                return NotFound();
            }
            return View(tsmp);
        }

        // POST: Tsmps/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Brand,Model,Type,TypeCode,RegNum,RegCountry,VinCode,EpiDocName")] Tsmp tsmp)
        {
            if (id != tsmp.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tsmp);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TsmpExists(tsmp.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tsmp);
        }

        // GET: Tsmps/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tsmp == null)
            {
                return NotFound();
            }

            var tsmp = await _context.Tsmp
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tsmp == null)
            {
                return NotFound();
            }

            return View(tsmp);
        }

        // POST: Tsmps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tsmp == null)
            {
                return Problem("Entity set 'EpiDbContext.Tsmp'  is null.");
            }
            var tsmp = await _context.Tsmp.FindAsync(id);
            if (tsmp != null)
            {
                _context.Tsmp.Remove(tsmp);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("Edit", "Epis", new { Id = Int32.Parse(tsmp.EpiDocName) });
        }

        private bool TsmpExists(int id)
        {
          return (_context.Tsmp?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Epis/Cancel.cshtml
@model PreInfoTrans.Models.Epi

@{
    ViewData["Title"] = "Аннулировать";
}

<h1 class="p-3 bg-warning bg-gradient">Аннулирование ЭПИ</h1>

<h3>Аннулировать сведения ЭПИ?</h3>

<div>
    <h4>ЭПИ № @Model.DocName</h4>
    <hr />
    <dl class="row ">
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.Result)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.Result)</dd>

        <dt class="col-sm-4 ">@Html.DisplayNameFor(m => m.DocDate)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.DocDate)</dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.DirectionIn)</dt>
        <dd class="col-sm-8 form-check form-check px-3">
            @{
                var checkIn = "Ввоз";
                if (!Model.DirectionIn) { checkIn = "Вывоз"; }
            }<button disabled class="btn btn-outline-primary btn-sm" type="button">@checkIn</button>
        </dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.Targets)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.Targets)</dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.TsmpFormatedString)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.TsmpFormatedString)</dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.RegNumTDTS)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.RegNumTDTS)</dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.RegDateTime)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.RegDateTime)</dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.RegNumOutTDTS)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.RegNumOutTDTS)</dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.RegComleteDateTime)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.RegComleteDateTime)</dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.RegCompleteTDTS)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.RegCompleteTDTS)</dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.RegEndDate)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.RegEndDate)</dd>
        <hr />
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.Route)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.Route)</dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.RouteCountry)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.RouteCountry)</dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.IsCrew)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.IsCrew)</dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.IsPassengers)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.IsPassengers)</dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.IsSupplies)</dt>
        <dd class="col-sm-8 form-check form-switch">
            @{
                var checkSupplies = "checked";
                if (!Model.IsSupplies) { checkSupplies = ""; }
            }<input class="form-check-input" type="checkbox" @checkSupplies disabled>
        </dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.IsGoods)</dt>
        <dd class="col-sm-8 form-check form-switch">
            @{
                var checkGoods = "checked";
                if (!Model.IsGoods) { checkGoods = ""; }
            }<input class="form-check-input" type="checkbox" @checkGoods disabled>
        </dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.SpareParts)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.SpareParts)</dd>
        <dt class="col-sm-4">@Html.DisplayNameFor(m => m.Description)</dt>
        <dd class="col-sm-8">@Html.DisplayFor(m => m.Description)</dd>
    </dl>
</div>
 <div>   
    <form asp-action="Cancel">
    <dt class="col-sm-4"><label asp-for="@Model.CancelReason" class="control-label col-form-label"></label></dt>
    <dd class="col-sm-5"><input asp-for="@Model.CancelReason" class="form-control" required oninvalid="this.setCustomValidity('Должна быть указана причина аннулирования!')"
       oninput="this.setCustomValidity('')" /></dd>
    <span asp-validation-for="@Model.CancelReason" class="text-danger"></span>
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Аннулировать" class="btn btn-warning" /> |
    <a type="buton" class="btn btn-secondary" asp-action="Index">Отмена</a>
    </form>
</div>

Views/Epis/Create.cshtml
@model PreInfoTrans.Models.Epi

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Epi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CreatorId" class="control-label"></label>
                <input asp-for="CreatorId" class="form-control" />
                <span asp-validation-for="CreatorId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="DirectionIn" /> @Html.DisplayNameFor(model => model.DirectionIn)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="DocName" class="control-label"></label>
                <input asp-for="DocName" class="form-control" readonly/>
                <span asp-validation-for="DocName" class="text-danger"></span>
            </div>
            <br />
            <p>
                <a asp-action="Create" class="btn btn-outline-primary" asp-controller="Tsmps" asp-route-docname="@Model.DocName">Добавить ТС</a>
            </p>
            <div class="form-group">
                <label asp-for="DocDate" class="control-label"></label>
                <input asp-for="DocDate" class="form-control" />
                <span asp-validation-for="DocDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegNumTDTS" class="control-label"></label>
                <input asp-for="RegNumTDTS" class="form-control" />
                <span asp-validation-for="RegNumTDTS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegDateTime" class="control-label"></label>
                <input asp-for="RegDateTime" class="form-control" />
                <span asp-validation-for="RegDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegNumOutTDTS" class="control-label"></label>
                <input asp-for="RegNumOutTDTS" class="form-control" />
                <span asp-validation-for="RegNumOutTDTS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Result" class="control-label"></label>
                <input asp-for="Result" class="form-control" />
                <span asp-validation-for="Result" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Route" class="control-label"></label>
                <input asp-for="Route" class="form-control" />
                <span asp-validation-for="Route" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RouteCountry" class="control-label"></label>
                <input asp-for="RouteCountry" class="form-control" />
                <span asp-validation-for="RouteCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsPassengers" class="control-label"></label>
                <input asp-for="IsPassengers" class="form-control" />
                <span asp-validation-for="IsPassengers" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsCrew" class="control-label"></label>
                <input asp-for="IsCrew" class="form-control" />
                <span asp-validation-for="IsCrew" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsSupplies" /> @Html.DisplayNameFor(model => model.IsSupplies)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsGoods" /> @Html.DisplayNameFor(model => model.IsGoods)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Targets" class="control-label"></label>
                <input asp-for="Targets" class="form-control" />
                <span asp-validation-for="Targets" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegCompleteTDTS" class="control-label"></label>
                <input asp-for="RegCompleteTDTS" class="form-control" />
                <span asp-validation-for="RegCompleteTDTS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegComleteDateTime" class="control-label"></label>
                <input asp-for="RegComleteDateTime" class="form-control" />
                <span asp-validation-for="RegComleteDateTime" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к журналу</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Epis/Delete.cshtml
@model PreInfoTrans.Models.Epi

@{
    ViewData["Title"] = "Удалить";
}

<h1>Удалить ЭПИ номер @Html.DisplayFor(model => model.DocName)</h1>

<h3>Подтвердить действие?</h3>
<div>
    <hr />
    <div class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Result)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Result)
        </dd>
    </div>

    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a type="buton" class="btn btn-secondary" asp-action="Index">Вернуться</a>
    </form>
</div>

Views/Epis/Reports.cshtml
@{
    ViewData["Title"] = "Отчеты";
}
<h1>@ViewData["Title"]</h1>

<p>Тут отображаются отчеты и статистика</p>